apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: b51ujrjuz-go 
  janus-idp.io/tekton: b51ujrjuz-go
  backstage.io/kubernetes-id: b51ujrjuz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b51ujrjuz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml